### ISSUE TITLE
aq-nmf-concordance should pick degrees

### ISSUE THREAD

**Issue by apmasell** [neufeld/AXIOME#1]
Rather than just produce the concordance graph, it should do some point-of-inflection magic to determine what degrees the user should try (possibly writing them back into the original `.aq` file).

**Comment by mwhall** [comment]
I've added a rudimentary version of this as the nmf-auto plugin. It works by giving aq-nmf-concordance the -auto flag, and it will look to find any local maxima, and will automatically run aq-nmf on that degree (if the degree is appropriate).

Problems with it are that it doesn't discriminate against things that are just barely maxima, and it automatically runs ALL maxima without asking the user. This could take a long time if, by chance, the output graph is a bit wavy. However, it's a nice thing to have for people with a lot of CPU time to burn while I dream something more elegant up.
